# Generated by Django 5.1.1 on 2024-09-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0002_clientdetails_reviewprice_userdetails_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
