# Generated by Django 5.1.1 on 2024-09-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0003_clientdetails_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetails',
            old_name='reviewer',
            new_name='total_reviews',
        ),
    ]
