# Generated by Django 5.1.1 on 2024-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0004_rename_reviewer_clientdetails_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
