# Generated by Django 5.1.1 on 2024-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0005_alter_clientdetails_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
