# Generated by Django 5.1.1 on 2024-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0006_alter_clientdetails_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='review',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
