# Generated by Django 5.1.1 on 2024-09-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0007_userhistory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
