# Generated by Django 5.1.1 on 2024-09-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0009_alter_userdetails_is_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
