# Generated by Django 5.1.1 on 2024-10-01 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0010_alter_userdetails_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhistory',
            name='link',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='verify_status',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
