# Generated by Django 5.1.1 on 2024-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0011_userhistory_created_at_userhistory_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
