# Generated by Django 5.1.1 on 2024-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0012_alter_userdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='image_path',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
