# Generated by Django 5.1.1 on 2024-10-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0013_clientdetails_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='review_link',
            field=models.CharField(max_length=2000),
        ),
    ]
