# Generated by Django 5.1.1 on 2024-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0014_alter_clientdetails_review_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='description',
            field=models.CharField(default='Cozy and inviting, our café offers the perfect atmosphere to relax, unwind, and enjoy delicious coffee and fresh pastries. Whether you are looking for a quiet corner to work, meet with friends, or simply savor a moment alone, we provide a warm and friendly environment. Our menu features a variety of specialty coffees, teas, and a selection of homemade treats made with the finest ingredients. Stop by for a cup of your favorite brew and experience the welcoming charm of our café.', max_length=1000),
        ),
    ]
