# Generated by Django 5.1.1 on 2024-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0015_clientdetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-08 12:16:24.434324'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='review_count',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='review_limit',
            field=models.CharField(default='3', max_length=100),
        ),
    ]
