# Generated by Django 5.1.1 on 2024-10-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0016_clientdetails_created_at_clientdetails_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
